// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensibilityMargin
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "182527ed-d306-4e47-9510-fca7fd83a32e";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidExtensibilityMarginPackageCmdSetString = "df59cf1c-76f7-407e-a6f9-86fa1583e830";
        public static Guid guidExtensibilityMarginPackageCmdSet = new Guid(guidExtensibilityMarginPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int MarginToggleCommandId = 0x0100;
    }
}