// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExtensibilityMargin
{
    internal sealed partial class Vsix
    {
        public const string Id = "41b4c077-6d9f-4e0a-a356-988baf3e830a";
        public const string Name = "Extensibility Margin";
        public const string Description = @"Shows relevant information about the current file and language to extensibility authors";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
